#!/usr/bin/env bash
# Only exported variables can be used within the timer's command.
export PRIMARY_DISPLAY="$(xrandr | awk '/ primary/{print $1}')"

# Run xidlehook
xidlehook \
	`# Don't lock when there's audio playing` \
	--not-when-audio \
	`# Finally, suspend an hour after it locks` \
	--timer 600 \
	'systemctl suspend' \
	''
