#!/bin/bash

# This script is to read a markdown file and open it in your browser. It assumes you have set your default browser.
#	Usage: readmd [FILE]
#	
#		FILE: A markdown formatted file.

pandoc -f markdown -t html $1 > /tmp/readmd.html
xdg-open /tmp/readmd.html
