#!/usr/bin/env bash
#
# Usage:
#   [PASSDIR=<password-store-directory>] rofipass

# Use default directory if no PASSDIR is set
[ -z $PASSDIR ] && export PASSDIR=$HOME/.password-store/

cd "$PASSDIR"

# Get the password name from rofi
name=$(ls **/*.gpg -1 | sed 's/\.gpg$//' | rofi -theme solarized_alternate -font 'sans-serif 16' -dmenu -i) 

# Copy the password to clipboard
[ -n "$name" ] && pass -c "$name"
