#!/usr/bin/env bash
#
# Usage:
#   rofipass

# Use default directory if no PASSDIR is set
[ -z $PASSWORD_STORE_DIR ] && export PASSWORD_STORE_DIR=$HOME/.password-store/

cd "$PASSWORD_STORE_DIR"

# Get the password name from rofi
name=$(ls **/*.gpg *.gpg -1 | sed 's/\.gpg$//' | rofi -theme solarized_alternate -font 'sans-serif 16' -dmenu -i) 

# Copy the password to clipboard
[ -n "$name" ] && pass -c "$name"
