#!/usr/bin/env bash
# Gets latest SDO images of sun and applies as wallpaper

cmd_wall='env DISPLAY=:1 nitrogen --set-auto'
cmd_dl='curl -LO'
sdo_url='https://sdo.gsfc.nasa.gov/assets/img/latest'
wall_1='latest_4096_0193.jpg'
wall_2='latest_4096_0304.jpg'

cd /tmp
$cmd_dl $sdo_url/$wall_1 && $cmd_wall --head=0 $wall_1
$cmd_dl $sdo_url/$wall_2 && $cmd_wall --head=1 $wall_2
